[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run db:push && npm run seed-admin && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production"

